# -*- coding: utf-8 -*-
"""Zadania Inzop EC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19iQVU7hmArocrJi0q3WsGqY9dtPoRZMW
"""

# Funkcja weryfikująca numer PESEL

def weryfikuj_pesel(pesel: str) -> int:
    wagi = [1, 3, 7, 9, 1, 3, 7, 9, 1, 3]
    suma = sum(int(pesel[i]) * wagi[i] for i in range(10))
    cyfra_kontrolna = (10 - (suma % 10)) % 10
    if cyfra_kontrolna == int(pesel[-1]):
        return 1
    else:
        return 0


przyklad_pesel = "02240404578"
wynik = weryfikuj_pesel(przyklad_pesel)
wynik

# Funkcja weryfikująca poprawność nawiasów
def poprawne_nawiasy(tekst: str) -> bool:
    licznik = 0

    for znak in tekst:
        if znak == '(':
            licznik += 1
        elif znak == ')':
            licznik -= 1
            if licznik < 0:
                return False

    return licznik == 0


przyklady_true = [
    "( if ( I ? x ) buy (/ 7 x ))",
    "I told ( that its yes ( just ) spring ). (42)"
]

przyklady_false = [
    ":-)",
    "Czesc (chyba coś mi nie poszło))",
    "())("
]

wyniki_true = [poprawne_nawiasy(przyklad) for przyklad in przyklady_true]
wyniki_false = [poprawne_nawiasy(przyklad) for przyklad in przyklady_false]

wyniki_true, wyniki_false